# Generated by Django 5.1.5 on 2025-04-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_enrolled_programs_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='instructions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='program',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='recommended_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mealplan'),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
